version: '3.8'

services:

  conversion-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2004:80"
    depends_on:
      - libreoffice-unoserver
    volumes:
      - shared-tmp:/tmp
    

  libreoffice-unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19
    volumes:
      - shared-tmp:/tmp

volumes:
  shared-tmp: